id: P004159
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:57:15.791998
source_metadata:
  id: bdr:W19692
  title: ལས་རབ་གླིང་པའི་རྣམ་ཐར
  author: ''
  volumes:
    2098976925004fc18ebc0f620d1c7f06:
      image_group_id: I5583
      title: ''
      volume_number: 1
      total_pages: 736
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
